#!/bin/bash

# 更新系统和安装依赖
sudo apt update -y
sudo apt install -y screen

# 新建目录
# 生成10位随机字母数字组合，然后进入目录
random_dir="dir_$(cat /dev/urandom | tr -dc 'a-zA-Z0-6' | fold -w 10 | head -n 1)"
mkdir -v $random_dir
cd $random_dir

#下载程序
wget https://github.com/rigelminer/rigel/releases/download/1.21.3/rigel-1.21.3-linux.tar.gz

#解压程序
tar -xzvf rigel-1.21.3-linux.tar.gz

#去rigel文件下
cd rigel-1.21.3-linux

# 创建快捷启动脚本
cat <<'EOF' > start
#!/bin/bash

# 生成随机矿工名
WORKER_NAME="$(date +"%Y%m%d_%H%M%S")"


# 启动挖矿程序并指定代理
screen -dmS ${WORKER_NAME} ./rigel -a quai -o stratum+tcp://cn.quai.k1pool.com:3333 -u KrWWj5jbMN9GXycYXaUFW4GM4xP5Fmq3Tgs -w RIG_NAME
# 输出通知
echo "你可以通过 'screen -r ${WORKER_NAME}' 来查看日志。"

EOF

# 设置执行权限
chmod +x start

# 启动脚本
./start

# 完成通知
echo "rigel 编译完成并已在后台运行！"
